# generated by appcreator
from django.contrib import admin
from . models import (
    Event,
    Work,
    Person,
    Place,
    Institution
)
admin.site.register(Event)
admin.site.register(Work)
admin.site.register(Person)
admin.site.register(Place)
admin.site.register(Institution)
