# generated by appcreator
from django.contrib import admin
from .models import Event, Work, Person, Place, Institution


@admin.register(Person)
class PersonAdmin(admin.ModelAdmin):
    model = Person
    search_fields = [
        "title",
    ]
    list_display = [
        "title",
        "gnd_gnd_id",
    ]


admin.site.register(Event)
admin.site.register(Work)
admin.site.register(Place)
admin.site.register(Institution)
