# generated by appcreator
from django.conf.urls import url
from . import dal_views

app_name = 'archiv'
urlpatterns = [
    url(
        r'^event-autocomplete/$',
        dal_views.EventAC.as_view(),
        name='event-autocomplete'
    ),
    url(
        r'^work-autocomplete/$',
        dal_views.WorkAC.as_view(),
        name='work-autocomplete'
    ),
]
