# generated by appcreator
from django.db.models import Q
from dal import autocomplete
from . models import (
    Event,
    Reference,
    Work
)


class EventAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Event.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(order_code__icontains=self.q)
            )
        return qs


class ReferenceAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Reference.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(id__icontains=self.q)
            )
        return qs


class WorkAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Work.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(order_code__icontains=self.q)
            )
        return qs
