# generated by appcreator
from django.urls import path
from . import dal_views

app_name = "archiv"
urlpatterns = [
    path("event-autocomplete", dal_views.EventAC.as_view(), name="event-autocomplete"),
    path("work-autocomplete", dal_views.WorkAC.as_view(), name="work-autocomplete"),
    path("wab-autocomplete", dal_views.WabAC.as_view(), name="wab-autocomplete"),
    path(
        "person-autocomplete", dal_views.PersonAC.as_view(), name="person-autocomplete"
    ),
    path("place-autocomplete", dal_views.PlaceAC.as_view(), name="place-autocomplete"),
    path(
        "institution-autocomplete",
        dal_views.InstitutionAC.as_view(),
        name="institution-autocomplete",
    ),
]
