# generated by appcreator
import django_tables2 as tables

from browsing.browsing_utils import MergeColumn
from . models import (
    Event,
    Reference,
    Work
)


class EventTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')
    key_word = tables.columns.ManyToManyColumn()
    reference = tables.columns.ManyToManyColumn()

    class Meta:
        model = Event
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class ReferenceTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Reference
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class WorkTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Work
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}

