# generated by appcreator
from django.urls import path
from . import views
from archiv.data_views import event_calendar_data, EventCalendarView

app_name = "archiv"
urlpatterns = [
    path("event-calendar-data", event_calendar_data, name="event_calendar_data"),
    path("event-calendar", EventCalendarView.as_view(), name="event_calendar"),
    path("event/", views.EventListView.as_view(), name="event_browse"),
    path(
        "event/detail/<int:pk>/",
        views.EventDetailView.as_view(),
        name="event_detail",
    ),
    path("event/create/", views.EventCreate.as_view(), name="event_create"),
    path("event/edit/<int:pk>/", views.EventUpdate.as_view(), name="event_edit"),
    path("event/delete/<int:pk>/", views.EventDelete.as_view(), name="event_delete"),
    path("work/", views.WorkListView.as_view(), name="work_browse"),
    path(
        "work/detail/<int:pk>/",
        views.WorkDetailView.as_view(),
        name="work_detail",
    ),
    path("work/create/", views.WorkCreate.as_view(), name="work_create"),
    path("work/edit/<int:pk>/", views.WorkUpdate.as_view(), name="work_edit"),
    path("work/delete/<int:pk>/", views.WorkDelete.as_view(), name="work_delete"),
    path("wab/", views.WabListView.as_view(), name="wab_browse"),
    path("wab/detail/<int:pk>/", views.WabDetailView.as_view(), name="wab_detail"),
    path("wab/create/", views.WabCreate.as_view(), name="wab_create"),
    path("wab/edit/<int:pk>/", views.WabUpdate.as_view(), name="wab_edit"),
    path("wab/delete/<int:pk>/", views.WabDelete.as_view(), name="wab_delete"),
    path("person/", views.PersonListView.as_view(), name="person_browse"),
    path(
        "person/detail/<int:pk>/",
        views.PersonDetailView.as_view(),
        name="person_detail",
    ),
    path("person/create/", views.PersonCreate.as_view(), name="person_create"),
    path("person/edit/<int:pk>/", views.PersonUpdate.as_view(), name="person_edit"),
    path(
        "person/delete/<int:pk>/",
        views.PersonDelete.as_view(),
        name="person_delete",
    ),
    path("place/", views.PlaceListView.as_view(), name="place_browse"),
    path(
        "place/detail/<int:pk>/",
        views.PlaceDetailView.as_view(),
        name="place_detail",
    ),
    path("place/create/", views.PlaceCreate.as_view(), name="place_create"),
    path("place/edit/<int:pk>/", views.PlaceUpdate.as_view(), name="place_edit"),
    path("place/delete/<int:pk>/", views.PlaceDelete.as_view(), name="place_delete"),
    path(
        "institution/", views.InstitutionListView.as_view(), name="institution_browse"
    ),
    path(
        "institution/detail/<int:pk>/",
        views.InstitutionDetailView.as_view(),
        name="institution_detail",
    ),
    path(
        "institution/create/",
        views.InstitutionCreate.as_view(),
        name="institution_create",
    ),
    path(
        "institution/edit/<int:pk>/",
        views.InstitutionUpdate.as_view(),
        name="institution_edit",
    ),
    path(
        "institution/delete/<int:pk>/",
        views.InstitutionDelete.as_view(),
        name="institution_delete",
    ),
]
