# Generated by Django 3.2.13 on 2022-07-04 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0002_auto_20220504_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='skoscollection',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Anmerkungen', null=True, verbose_name='Anmerkungen generell'),
        ),
    ]
