# Generated by Django 3.2.13 on 2022-07-04 07:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0003_skoscollection_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skoscollection',
            name='remarks',
        ),
        migrations.AddField(
            model_name='skosconcept',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Anmerkungen', null=True, verbose_name='Anmerkungen generell'),
        ),
    ]
