# Generated by Django 4.1.3 on 2023-03-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabs", "0004_auto_20220704_0714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skosconcept",
            name="pref_label",
            field=models.CharField(
                help_text="Titel des Schlagwortes", max_length=300, verbose_name="Titel"
            ),
        ),
    ]
