# Generated by Django 5.1.7 on 2025-03-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabs", "0005_alter_skosconcept_pref_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skosconcept",
            options={
                "ordering": ["pref_label"],
                "verbose_name": "Schlagwort",
                "verbose_name_plural": "Schlagwörter",
            },
        ),
        migrations.RemoveField(
            model_name="skosconcept",
            name="level",
        ),
        migrations.RemoveField(
            model_name="skosconcept",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="skosconcept",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="skosconcept",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="skosconcept",
            name="broader_concept",
            field=models.ForeignKey(
                blank=True,
                help_text="Concept with a broader meaning that this concept inherits from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="narrower_concepts",
                to="vocabs.skosconcept",
                verbose_name="skos:broader",
            ),
        ),
    ]
