# Generated by Django 3.2.11 on 2022-02-01 10:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='whatever', null=True, verbose_name='Haupttext'),
        ),
        migrations.AlterField(
            model_name='event',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, help_text='whatever', null=True, verbose_name='Allgemeine Anmkerungen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes_archive',
            field=ckeditor.fields.RichTextField(blank=True, help_text='whatever', null=True, verbose_name='Anmerkungen Archiv'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes_facs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='whatever', null=True, verbose_name='Anmerkungen Faksimiles'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes_img',
            field=ckeditor.fields.RichTextField(blank=True, help_text='whatever', null=True, verbose_name='Anmerkungen Abbildungen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes_lit',
            field=ckeditor.fields.RichTextField(blank=True, help_text='whatever', null=True, verbose_name='Anmerkungen Literatur'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='whatever', null=True, verbose_name='Anmerkungen Text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='orig_data_csv',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='The original data'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='orig_data_csv',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='The original data'),
        ),
        migrations.AlterField(
            model_name='work',
            name='orig_data_csv',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='The original data'),
        ),
    ]
