# Generated by Django 3.2.12 on 2022-02-04 15:33

from django.db import migrations, models
import gnd.fields


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0002_alter_work_full_quote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gnd_gnd_id", gnd.fields.GndField(blank=True, null=True, unique=True)),
                (
                    "gnd_pref_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("gnd_payload", models.JSONField(blank=True, null=True)),
                ("gnd_created", models.DateTimeField(blank=True, null=True)),
                ("gnd_gender", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "gnd_birth_date_written",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "gnd_death_date_written",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("gnd_birth_date", models.DateField(blank=True, null=True)),
                ("gnd_death_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
