# Generated by Django 3.2.12 on 2022-03-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0008_auto_20220318_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='orig_data_csv',
        ),
    ]
