# Generated by Django 3.2.12 on 2022-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0011_wab"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="wab",
            field=models.ManyToManyField(
                blank=True,
                related_name="rvn_wab_mentioned_in",
                to="archiv.Wab",
                verbose_name="erwähnte Bruckner Werke (WAB)",
            ),
        ),
    ]
