# Generated by Django 3.2.12 on 2022-04-29 10:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0013_auto_20220419_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='work',
            name='full_quote',
            field=ckeditor.fields.RichTextField(blank=True, help_text='whatever', null=True, verbose_name='Langzitat'),
        ),
    ]
