# Generated by Django 3.2.13 on 2022-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0019_auto_20220525_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='remarks',
            field=models.TextField(blank=True, help_text='Anmerkungen zur Person', null=True, verbose_name='Anmerkungen'),
        ),
    ]
