# Generated by Django 3.2.13 on 2022-06-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0020_person_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="key_word",
            field=models.TextField(
                blank=True,
                help_text="Feld für interne Notizen und Stichworte",
                null=True,
                verbose_name="Stichwort",
            ),
        ),
    ]
