# Generated by Django 3.2.13 on 2022-06-23 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0024_auto_20220623_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Anmerkungen zum Ort', null=True, verbose_name='Anmerkungen generell'),
        ),
    ]
