# Generated by Django 3.2.13 on 2022-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0026_auto_20220623_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='work',
            field=models.ManyToManyField(blank=True, help_text='Literaturangaben zu dieser Person', related_name='work_referenced_in_person', to='archiv.Work', verbose_name='Literatur'),
        ),
    ]
