# Generated by Django 3.2.13 on 2022-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0027_person_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="work",
            field=models.ManyToManyField(
                blank=True,
                help_text="Literaturangaben zu diesem Ort",
                related_name="work_referenced_in_place",
                to="archiv.Work",
                verbose_name="Literatur",
            ),
        ),
    ]
