# Generated by Django 3.2.13 on 2022-07-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0031_auto_20220726_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname']},
        ),
    ]
