# Generated by Django 3.2.13 on 2022-08-10 14:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0032_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wab",
            name="note",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen und Erläuterungen",
                null=True,
                verbose_name="Anmerkungen",
            ),
        ),
    ]
