# Generated by Django 3.2.13 on 2022-08-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0033_alter_wab_note"),
        ("archiv", "0033_auto_20220801_0828"),
    ]

    operations = []
