# Generated by Django 3.2.15 on 2022-11-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0036_create_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='orig_data_csv',
        ),
    ]
