# Generated by Django 4.1.3 on 2023-03-28 08:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0037_auto_20221128_1305"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wab",
            options={"ordering": ["wab_id"], "verbose_name": "Werke Bruckners"},
        ),
        migrations.AlterField(
            model_name="event",
            name="date_written",
            field=models.CharField(
                blank=True,
                help_text="Datierung des Eintrages",
                max_length=250,
                null=True,
                verbose_name="Datum",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="institution",
            field=models.ManyToManyField(
                blank=True,
                help_text="Verknüpfungen zu erwähnten Institutionen",
                related_name="institution_mentioned_in",
                to="archiv.institution",
                verbose_name="erwähnte Institutionen",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="not_after",
            field=models.DateField(
                blank=True,
                help_text="Maschinenlesbare Datierung des Eintrages.            Bei einem mehrtägigem Ereigniss wird das Enddatum verzeichnet.",
                null=True,
                verbose_name="nicht danach",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="not_before",
            field=models.DateField(
                blank=True,
                help_text="Maschinenlesbare Datierung des Eintrages.            Bei einem mehrtägigem Ereigniss wird das Anfangsdatum verzeichnet.",
                null=True,
                verbose_name="nicht bevor",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="note",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Allgemeine Anmerkungen",
                null=True,
                verbose_name="Allgemeine Anmerkungen",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes_archive",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Archiv",
                null=True,
                verbose_name="Archiv",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes_facs",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Faksimiles",
                null=True,
                verbose_name="Faksimiles",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes_img",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Abbildungen",
                null=True,
                verbose_name="Abbildungen",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes_lit",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Literatur",
                null=True,
                verbose_name="Literatur",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes_text",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Anmerkung",
                null=True,
                verbose_name="Anmerkungen",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="person",
            field=models.ManyToManyField(
                blank=True,
                help_text="Verknüpfungen zu erwähnten Personen",
                related_name="rvn_person_mentioned_in",
                to="archiv.person",
                verbose_name="erwähnte Personen",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.ManyToManyField(
                blank=True,
                help_text="Verknüpfungen zu erwähnten Orten",
                related_name="place_mentioned_in",
                to="archiv.place",
                verbose_name="erwähnte Orte",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="wab",
            field=models.ManyToManyField(
                blank=True,
                help_text="Verknüpfungen zu Bruckners Werken",
                related_name="rvn_wab_mentioned_in",
                to="archiv.wab",
                verbose_name="erwähnte Bruckner Werke (WAB)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="work",
            field=models.ManyToManyField(
                blank=True,
                help_text="Literaturangaben zu diesem Ereignis",
                related_name="work_referenced_in",
                to="archiv.work",
                verbose_name="Bibliographie",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="notes_archive",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Archiv",
                null=True,
                verbose_name="Anmerkungen Archiv",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="notes_facs",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Faksimiles",
                null=True,
                verbose_name="Anmerkungen Faksimiles",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="notes_img",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Abbildungen",
                null=True,
                verbose_name="Anmerkungen Abbildungen",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="surname",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Nachname"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Vorname Nachname",
                max_length=250,
                null=True,
                verbose_name="Voller Name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="work",
            field=models.ManyToManyField(
                blank=True,
                help_text="Literaturangaben zu dieser Person",
                related_name="work_referenced_in_person",
                to="archiv.work",
                verbose_name="Bibliographie",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="notes_archive",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Archiv",
                null=True,
                verbose_name="Anmerkungen Archiv",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="notes_facs",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Faksimiles",
                null=True,
                verbose_name="Anmerkungen Faksimiles",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="notes_img",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Anmerkungen zum Abschnitt Abbildungen",
                null=True,
                verbose_name="Anmerkungen Abbildungen",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="work",
            field=models.ManyToManyField(
                blank=True,
                help_text="Literaturangaben zu diesem Ort",
                related_name="work_referenced_in_place",
                to="archiv.work",
                verbose_name="Bibliographie",
            ),
        ),
        migrations.AlterField(
            model_name="wab",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="z.B. 1874-12-24",
                null=True,
                verbose_name="Datierung",
            ),
        ),
        migrations.AlterField(
            model_name="wab",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Werkstitel und WAB Nummer",
                max_length=250,
                null=True,
                verbose_name="Werk",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="author_name",
            field=models.CharField(
                blank=True,
                help_text="Name der Autorin/des Autors",
                max_length=250,
                null=True,
                verbose_name="Autorenname",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="full_quote",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Vollsständige bibliographische Angabe",
                null=True,
                verbose_name="Langzitat",
            ),
        ),
    ]
